// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: BannerService.proto

package rotatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlotBanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID   int64 `protobuf:"varint,1,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	BannerID int64 `protobuf:"varint,2,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
}

func (x *SlotBanner) Reset() {
	*x = SlotBanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BannerService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotBanner) ProtoMessage() {}

func (x *SlotBanner) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotBanner.ProtoReflect.Descriptor instead.
func (*SlotBanner) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{0}
}

func (x *SlotBanner) GetSlotID() int64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *SlotBanner) GetBannerID() int64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

type BannerSlotGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerID int64 `protobuf:"varint,1,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
	SlotID   int64 `protobuf:"varint,2,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	GroupID  int64 `protobuf:"varint,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *BannerSlotGroup) Reset() {
	*x = BannerSlotGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BannerService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerSlotGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerSlotGroup) ProtoMessage() {}

func (x *BannerSlotGroup) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerSlotGroup.ProtoReflect.Descriptor instead.
func (*BannerSlotGroup) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{1}
}

func (x *BannerSlotGroup) GetBannerID() int64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

func (x *BannerSlotGroup) GetSlotID() int64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *BannerSlotGroup) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

type SlotGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID  int64 `protobuf:"varint,1,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	GroupID int64 `protobuf:"varint,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *SlotGroup) Reset() {
	*x = SlotGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BannerService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotGroup) ProtoMessage() {}

func (x *SlotGroup) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotGroup.ProtoReflect.Descriptor instead.
func (*SlotGroup) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{2}
}

func (x *SlotGroup) GetSlotID() int64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *SlotGroup) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

type Banner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerID int64 `protobuf:"varint,1,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
}

func (x *Banner) Reset() {
	*x = Banner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BannerService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_BannerService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_BannerService_proto_rawDescGZIP(), []int{3}
}

func (x *Banner) GetBannerID() int64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

var File_BannerService_proto protoreflect.FileDescriptor

var file_BannerService_proto_rawDesc = []byte{
	0x0a, 0x13, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0a, 0x53,
	0x6c, 0x6f, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6c, 0x6f,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x5f, 0x0a,
	0x0f, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x6c,
	0x6f, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x3d,
	0x0a, 0x09, 0x53, 0x6c, 0x6f, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x6c, 0x6f,
	0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x24, 0x0a,
	0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x49, 0x44, 0x32, 0xe6, 0x01, 0x0a, 0x07, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x34, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x13, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x13, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3b,
	0x0a, 0x05, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x12, 0x18, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x06, 0x43,
	0x68, 0x6f, 0x6f, 0x73, 0x65, 0x12, 0x12, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x53, 0x6c, 0x6f, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x0f, 0x2e, 0x72, 0x6f, 0x74, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x3b, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_BannerService_proto_rawDescOnce sync.Once
	file_BannerService_proto_rawDescData = file_BannerService_proto_rawDesc
)

func file_BannerService_proto_rawDescGZIP() []byte {
	file_BannerService_proto_rawDescOnce.Do(func() {
		file_BannerService_proto_rawDescData = protoimpl.X.CompressGZIP(file_BannerService_proto_rawDescData)
	})
	return file_BannerService_proto_rawDescData
}

var file_BannerService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_BannerService_proto_goTypes = []interface{}{
	(*SlotBanner)(nil),      // 0: rotator.SlotBanner
	(*BannerSlotGroup)(nil), // 1: rotator.BannerSlotGroup
	(*SlotGroup)(nil),       // 2: rotator.SlotGroup
	(*Banner)(nil),          // 3: rotator.Banner
	(*emptypb.Empty)(nil),   // 4: google.protobuf.Empty
}
var file_BannerService_proto_depIdxs = []int32{
	0, // 0: rotator.Rotator.Add:input_type -> rotator.SlotBanner
	0, // 1: rotator.Rotator.Delete:input_type -> rotator.SlotBanner
	1, // 2: rotator.Rotator.Click:input_type -> rotator.BannerSlotGroup
	2, // 3: rotator.Rotator.Choose:input_type -> rotator.SlotGroup
	4, // 4: rotator.Rotator.Add:output_type -> google.protobuf.Empty
	4, // 5: rotator.Rotator.Delete:output_type -> google.protobuf.Empty
	4, // 6: rotator.Rotator.Click:output_type -> google.protobuf.Empty
	3, // 7: rotator.Rotator.Choose:output_type -> rotator.Banner
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_BannerService_proto_init() }
func file_BannerService_proto_init() {
	if File_BannerService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_BannerService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotBanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_BannerService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerSlotGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_BannerService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_BannerService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BannerService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_BannerService_proto_goTypes,
		DependencyIndexes: file_BannerService_proto_depIdxs,
		MessageInfos:      file_BannerService_proto_msgTypes,
	}.Build()
	File_BannerService_proto = out.File
	file_BannerService_proto_rawDesc = nil
	file_BannerService_proto_goTypes = nil
	file_BannerService_proto_depIdxs = nil
}
