[logger]
level = "INFO"

[db]
# migration = "migrations"
# dsn = "host=localhost port=5432 user=postgres password=postgres dbname=storage sslmode=disable"

migration = "/etc/migrations"
dsn = "host=postgres port=5432 user=postgres password=postgres dbname=storage sslmode=disable"

[grpcserver]
network = "tcp"
address = ":50051"

[rabbit]
uri = "amqp://guest:guest@rabbitmq:5672/"
queue = "messages"
exchange = "rotator"
kind = "direct"
